name: Docker Image CI

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 2 * * 0'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Generate build number
      id: buildnumber
      uses: einaregilsson/build-number@v3 
      with:
        token: ${{secrets.TOKEN}} 
    - name: Publish Docker
      uses: elgohr/Publish-Docker-Github-Action@3.04
    
      with:
        name: pon0mar/homework3
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: ${{ steps.buildnumber.outputs.build_number }}
